# Generated by Django 4.2.7 on 2023-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
